apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-tts
  labels:
    app: edge-tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-tts
  template:
    metadata:
      name: edge-tts
      labels:
        app: edge-tts
    spec:
      containers:
        - name: edge-tts
          image: ghcr.io/parzival-space/openai-edge-tts:v2.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: edge-tts
          ports:
            - name: openai-voice
              containerPort: 5050
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always

