namespace: open-webui

resources:
  - edge-tts.config-map.yaml
  - edge-tts.deployment.yaml
  - edge-tts.service.yaml
  - open-webui.helm-release.yaml
  - open-webui.helm-repository.yaml
  - open-webui.namespace.yaml
  - open-webui-values.config-map.yaml
  - open-webui-values.secret.yaml
  - playwright.service.yaml
  - playwright.stateful-set.yaml

configMapGenerator:
  - name: open-webui-pipelines
    options:
      disableNameSuffixHash: true
    files:
      - pipelines/token_limit_pipeline.py
