apiVersion: v1
kind: Secret
metadata:
    name: open-webui-values
    namespace: open-webui
stringData:
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:YEQYGIdhV0oVHlOmlg3OoTvE8ATOWeURWjN8bWtt39566hqNAN+yRB3DoA6KPqk4t44qLbyqz6ekG9mvKCAyV3H1Bchl8uo6mQ==,iv:X5Fv6cQ1Qm5PU9yF9bX/z7fCMuhF+NaQ7WiCNcJFudo=,tag:cfssKh6HRlzloihLQZ66Bw==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:3jWB1NQMiYu9+WSq0Mxkb0nw8l3fTRgdPHdRwm32WA==,iv:6n4jCNmPJ4+E5Ff452udjuZkQGDiOe7typgmGH+SNJE=,tag:0q0jn452VMCMUWxMK4xHag==,type:str]
    values.yaml: ENC[AES256_GCM,data:OJo2q89xL2E0J2GP0SdcKxQSGcUjDQOCesklPeSIF/sPXRtM/nhZkA6Xyp+9EpwXTJLGpL8evH1SCxoevu/EnJNqpdwYW4w5i6Ti0PlrjvhjGMaXiQHXCefiaAwfla1ddM+lNZLTwL2Nhim8heP451ltYPVYC1yASFNQEbjbT5RfxkjAivPl7l+2lusy4AbqmcQnY6BOrvj6JMtbnerjjRYuwkwiPKw9Dj/8eX97NtVnO8nrfvH6+pkEteLsfGRd0kv503kfAA9QPfI4TIuZalNqQEWKEdOXFn5JlpLwEyewW9orXe6thJtYtj4shpueWalQG/d9Ycyg9xKgHdcsLEAiEVXkivAge93jwArz9uSSoXmPrsj+VGWZ4gFsyCnf64jsLdcriJn7lJjcbo7t+Az9xuwuzhKnDuWc1w75SzCqZO1PrzLfdl12QBUNye2r1MJVjoQy+Szg7SJjEtTXZneHe8pIYU6E7eGYcc7+LZ/7LnJl8mOPRTZLLnxwU7bGPhe8tYQNp5+Zlhecy7KuHFM1E0U9fG6VJygEQX3oyzW+DNsuzHRiqpdJ2x9GKxzt9PWBx7r+DDMhMkQEmVmRw4YS5krnKGeqfi9PH17ROHcdPXzTX4HweCHtbbgV724NejQ3fpMATPLAcGuewO6asUBaZ53cZfivRWF/hW26rJ+f7vkCraVepOuemeYtKiKbGhySOAbycvJdZThkH69O4ylRBVv6WN36rsV+J0W/JJk7Gre0hCSqL1J9X+vivx5t1D4U7UFXZul+Z78G6Fj1z2+kNT0yfGWqGtu5xZkti1SwHSGQxATUGSnBAYxYDkr7FQ827sN6OfcMORB+43zuYatbj0UYvjIpa1asKqHMQ/+jMgdCrilV4ST7a1sjHqa8LGu6odg=,iv:f+gm3a/ffz206c45AJ57x+ylKxgnE+RZmNB6ujDQyzg=,tag:VS3ExY0NCgED7CluthV6Xw==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TThDa0xMUkFRelJncE9U
            L0NWbklCeTVsRGEyWkNQYXl0ZDBkRzgrZno4CjRWR2FNSS9zaVFROVZ6RFpCeE5C
            ZTBLWmJndkRBUDNuZ2w4UmoxcFpnd0UKLS0tIFIxc0lPb0dvTE15SzNOUXA4QXh6
            blRwRUw0Yjk3bFc1T2ZXYlhldlN0TVEKhiUDZaFpnPpVN+c0H31mkd5XlMqGAheI
            7TPgkS2ytOnvsGFfagm6T+8FlAEKEg9wT6W9r3O91JHw7grlN8CAoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T17:53:58Z"
    mac: ENC[AES256_GCM,data:/suTn49gANbIjdjTjLWfEDqaAb4E8/tC/IbiGyvapJw0wUH3f6k1FiyNCSDdg65yMhEwNDqVu3H4E/HLMUNOw6Y0XI17f2uWQopuy4rB+avY1hVgx2AM/9z1qfZ34UQVRZcg9JS/GeeVfVghjSMfwPkD5skM11AcNG1n3ZrICu4=,iv:OM16qRccmtAJdckcZYjYQzTI4l6w9ukDf9fSK1On4IM=,tag:31f5kIxUIpusffPpWOqT4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
