apiVersion: v1
kind: Secret
metadata:
    name: open-webui-values
    namespace: open-webui
stringData:
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:jGAaEw==,iv:P6LoB6hkcmyx6GXI9FC14QVSjuu0UdISucg8l95kTF8=,tag:5ggrTsAdP/AWawsJZH6zNQ==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:E51TPBGhJZADMbli057lNhzh3F8pRraSoFPr7fng2A==,iv:uQQmZ2Wr+Jr+GRqK0qadzmCPg2T8zkpTDpbBcqNXQGo=,tag:FAYiaOSoPjS3qhiJk1v0gw==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:YEQYGIdhV0oVHlOmlg3OoTvE8ATOWeURWjN8bWtt39566hqNAN+yRB3DoA6KPqk4t44qLbyqz6ekG9mvKCAyV3H1Bchl8uo6mQ==,iv:X5Fv6cQ1Qm5PU9yF9bX/z7fCMuhF+NaQ7WiCNcJFudo=,tag:cfssKh6HRlzloihLQZ66Bw==,type:str]
    values.yaml: ENC[AES256_GCM,data:OJo2q89xL2E0J2GP0SdcKxQSGcUjDQOCesklPeSIF/sPXRtM/nhZkA6Xyp+9EpwXTJLGpL8evH1SCxoevu/EnJNqpdwYW4w5i6Ti0PlrjvhjGMaXiQHXCefiaAwfla1ddM+lNZLTwL2Nhim8heP451ltYPVYC1yASFNQEbjbT5RfxkjAivPl7l+2lusy4AbqmcQnY6BOrvj6JMtbnerjjRYuwkwiPKw9Dj/8eX97NtVnO8nrfvH6+pkEteLsfGRd0kv503kfAA9QPfI4TIuZalNqQEWKEdOXFn5JlpLwEyewW9orXe6thJtYtj4shpueWalQG/d9Ycyg9xKgHdcsLEAiEVXkivAge93jwArz9uSSoXmPrsj+VGWZ4gFsyCnf64jsLdcriJn7lJjcbo7t+Az9xuwuzhKnDuWc1w75SzCqZO1PrzLfdl12QBUNye2r1MJVjoQy+Szg7SJjEtTXZneHe8pIYU6E7eGYcc7+LZ/7LnJl8mOPRTZLLnxwU7bGPhe8tYQNp5+Zlhecy7KuHFM1E0U9fG6VJygEQX3oyzW+DNsuzHRiqpdJ2x9GKxzt9PWBx7r+DDMhMkQEmVmRw4YS5krnKGeqfi9PH17ROHcdPXzTX4HweCHtbbgV724NejQ3fpMATPLAcGuewO6asUBaZ53cZfivRWF/hW26rJ+f7vkCraVepOuemeYtKiKbGhySOAbycvJdZThkH69O4ylRBVv6WN36rsV+J0W/JJk7Gre0hCSqL1J9X+vivx5t1D4U7UFXZul+Z78G6Fj1z2+kNT0yfGWqGtu5xZkti1SwHSGQxATUGSnBAYxYDkr7FQ827sN6OfcMORB+43zuYatbj0UYvjIpa1asKqHMQ/+jMgdCrilV4ST7a1sjHqa8LGu6odg=,iv:f+gm3a/ffz206c45AJ57x+ylKxgnE+RZmNB6ujDQyzg=,tag:VS3ExY0NCgED7CluthV6Xw==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TThDa0xMUkFRelJncE9U
            L0NWbklCeTVsRGEyWkNQYXl0ZDBkRzgrZno4CjRWR2FNSS9zaVFROVZ6RFpCeE5C
            ZTBLWmJndkRBUDNuZ2w4UmoxcFpnd0UKLS0tIFIxc0lPb0dvTE15SzNOUXA4QXh6
            blRwRUw0Yjk3bFc1T2ZXYlhldlN0TVEKhiUDZaFpnPpVN+c0H31mkd5XlMqGAheI
            7TPgkS2ytOnvsGFfagm6T+8FlAEKEg9wT6W9r3O91JHw7grlN8CAoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:05:31Z"
    mac: ENC[AES256_GCM,data:rxkQOVtIMfKeo9kpV0Xb/Ug6XaJ5+TeTb1vkyZhud0SFDfc0s70gb6R7MZmE4WoeKWg39rOW+AmC3ecxkw06HBvx20bsXNhcaB/eTDEGwqBaJNTVTOOFXWaWT6JM9wPE7dwlnvKwjvID5Y4GnLRj9pPEjpmjiWRNLOExh1vccio=,iv:B6KxGIQXjX/z95He4z4/XidXfUAcnNo1eSFifJ8rReY=,tag:kBIaWz8DQsr4t8iP69jb5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
