apiVersion: v1
kind: ConfigMap
metadata:
  name: open-webui-values
  namespace: open-webui
data:
  ENABLE_PERSISTENT_CONFIG: "False"
  WEBUI_URL: "https://ai.parzi.cloud"

  # oauth settings
  ENABLE_LOGIN_FORM: "False"
  ENABLE_OAUTH_PERSISTENT_CONFIG: "False"
  OAUTH_UPDATE_PICTURE_ON_LOGIN: "True"

  # rag settings
  RAG_OPENAI_API_BASE_URL: "https://openrouter.ai/api/v1"
  RAG_RERANKING_MODEL_AUTO_UPDATE: "False"
  RAG_RERANKING_MODEL_TRUST_REMOTE_CODE: "False"
  RAG_EMBEDDING_ENGINE: "openai"
  RAG_EMBEDDING_MODEL: "qwen/qwen3-embedding-8b"
  RAG_EMBEDDING_MODEL_AUTO_UPDATE: "False"
  RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE: "False"

  # user defaults
  DEFAULT_USER_ROLE: "user"
  DEFAULT_MODELS: "switchpoint/router"

  # all user have access to all models
  BYPASS_MODEL_ACCESS_CONTROL: "False"

  # upload limitations
  FOLDER_MAX_FILE_COUNT: "3"

  # feature toggles
  ENABLE_CHANNELS: "True"
  ENABLE_FOLDERS: "True"
  ENABLE_NOTES: "True"
  ENABLE_MEMORIES: "True"
  ENABLE_USER_WEBHOOKS: "False"
  ENABLE_TITLE_GENERATION: "True"
  ENABLE_EVALUATION_ARENA_MODELS: "False"
  ENABLE_TAGS_GENERATION: "False"
  ENABLE_API_KEYS: "False" # disable user api keys for now
  ENABLE_WEB_SEARCH: "True"
  ENABLE_IMAGE_GENERATION: "False" # no nodes available for this feature

  # reduce admin access (user privacy)
  ENABLE_ADMIN_EXPORT: "False"
  ENABLE_ADMIN_CHAT_ACCESS: "False"
  ENABLE_ADMIN_WORKSPACE_CONTENT_ACCESS: "False" # deprecated, use below
  BYPASS_ADMIN_ACCESS_CONTROL: "False"

  # feature: code execution
  ENABLE_CODE_EXECUTION: "True"
  CODE_EXECUTION_ENGINE: "pyodide"
  ENABLE_CODE_INTERPRETER: "True"
  CODE_INTERPRETER_ENGINE: "pyodide"

  # feature: autocomplete
  ENABLE_AUTOCOMPLETE_GENERATION: "False"

  # feature: web search
  ENABLE_SEARCH_QUERY_GENERATION: "True"
  WEB_SEARCH_CONCURRENT_REQUESTS: "1"
  WEB_SEARCH_ENGINE: "duckduckgo"
  DDGS_BACKEND: "duckduckgo"

  # text-to-speech settings
  AUDIO_TTS_ENGINE: "openai"
  AUDIO_TTS_MODEL: "tts-1-hd"
  AUDIO_TTS_VOICE: "de-DE-FlorianMultilingualNeural"
  AUDIO_TTS_SPLIT_ON: "punctuation"
  AUDIO_TTS_OPENAI_API_BASE_URL: "http://edge-tts.open-webui.svc.cluster.local:5050/v1"
  AUDIO_TTS_OPENAI_API_KEY: "edge_tts_pseudo_api_key"
  AUDIO_TTS_API_KEY: "edge_tts_pseudo_api_key" # I don't know why this exists

  # user permissions: chat
  USER_PERMISSIONS_CHAT_CONTROLS: "True" # allow users to control chat settings
  USER_PERMISSIONS_CHAT_VALVES: "False"
  USER_PERMISSIONS_CHAT_SYSTEM_PROMPT: "True"
  USER_PERMISSIONS_CHAT_PARAMS: "True"
  USER_PERMISSIONS_CHAT_FILE_UPLOAD: "True"
  USER_PERMISSIONS_CHAT_DELETE: "True"
  USER_PERMISSIONS_CHAT_EDIT: "True"
  USER_PERMISSIONS_CHAT_DELETE_MESSAGE: "True"
  USER_PERMISSIONS_CHAT_CONTINUE_RESPONSE: "False" # broken anyway
  USER_PERMISSIONS_CHAT_REGENERATE_RESPONSE: "True"
  USER_PERMISSIONS_CHAT_RATE_RESPONSE: "True"
  USER_PERMISSIONS_CHAT_STT: "True"
  USER_PERMISSIONS_CHAT_TTS: "True"
  USER_PERMISSIONS_CHAT_CALL: "True"
  USER_PERMISSIONS_CHAT_MULTIPLE_MODELS: "False" # disable multiple models per chat
  USER_PERMISSIONS_CHAT_TEMPORARY: "True"
  USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED: "False" # forces temporary chats to stay temporary

  # user permissions: features
  USER_PERMISSIONS_FEATURES_DIRECT_TOOL_SERVERS: "False" # disable direct tool servers access
  USER_PERMISSIONS_FEATURES_WEB_SEARCH: "True"
  USER_PERMISSIONS_FEATURES_IMAGE_GENERATION: "False" # no nodes available for this feature
  USER_PERMISSIONS_FEATURES_CODE_INTERPRETER: "True"
  USER_PERMISSIONS_FEATURES_MEMORIES: "True"
  USER_PERMISSIONS_FEATURES_FOLDERS: "True"
  USER_PERMISSIONS_FEATURES_NOTES: "True"
  USER_PERMISSIONS_FEATURES_CHANNELS: "True" # enable group channels
  USER_PERMISSIONS_FEATURES_API_KEYS: "False" # disable user api keys for now

  # user permissions: workspace
  USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS: "False"
  USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS: "True"
  USER_PERMISSIONS_WORKSPACE_PROMPTS_ACCESS: "True"
  USER_PERMISSIONS_WORKSPACE_TOOLS_ACCESS: "True"
  USER_PERMISSIONS_WORKSPACE_MODELS_ALLOW_PUBLIC_SHARING: "True" # users don't have access anyway
  USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ALLOW_PUBLIC_SHARING: "True"
  USER_PERMISSIONS_WORKSPACE_PROMPTS_ALLOW_PUBLIC_SHARING: "False"
  USER_PERMISSIONS_WORKSPACE_TOOLS_ALLOW_PUBLIC_SHARING: "False"
  USER_PERMISSIONS_NOTES_ALLOW_PUBLIC_SHARING: "False"

  # user permissions: settings
  USER_PERMISSIONS_SETTINGS_INTERFACE: "True" # allow users to change interface settings

  values.yaml: |
    image:
      repository: "ghcr.io/open-webui/open-webui"
      tag: "v0.7.2"

    # set according resource, since we are running a whisper model
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "750m"
        memory: "2Gi"


    # disable ollama (enabled by default)
    ollama:
      enabled: false

    ingress:
      enabled: true
      class: traefik
      tls: false
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      host: "ai.parzi.cloud"

    persistence:
      enabled: true
      size: 5Gi
      storageClass: longhorn

    logging:
      level: debug

    # some sensitive credentials are stored in the values secret
    extraEnvFrom:
      - configMapRef:
          name: open-webui-values
      - secretRef:
          name: open-webui-values

