apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    #ENC[AES256_GCM,data:ADs5YmPgBQZ0Qqc9Swnpc48Agj6DZXPSUzg3bewhfA==,iv:edmpw7MToCQYZQm7W/ZM/2Sqy4tHPDMjS35RuouDQzM=,tag:d1nd6p3zmYPdRhsWTrbh0Q==,type:comment]
    PROVIDER_OAUTH_DISCORD_CLIENT_ID: ENC[AES256_GCM,data:EcHdEY9vxWrrgz3oxwAV0gt/6Q==,iv:rbcBnWF6NPVzu2W5Vdg55hF9BTjWOCgEP79M0g5lQCQ=,tag:2RWxs1zSVLRWgt0D+FirRg==,type:str]
    PROVIDER_OAUTH_DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:cSlHJIDZ42UHqESN1IPsLTY0/lHWGo4beSQ3F4gHPKw=,iv:1bzNp31pEMTC4C+NnJJREuh8K5SHvXWEeu4FA651Htk=,tag:XICKY/jEd6dWvCI1AlR8Fw==,type:str]
    #ENC[AES256_GCM,data:xc0J14os8E0XJtoB9JIHpg7rpfm8ZD1G/mBrhQ==,iv:JGAyMhJNjoKBokAAmdnBYLWeezEUCFQSMSBE4EpJDL8=,tag:c44lyt/Ye+DnEknYPBJq2w==,type:comment]
    APPLICATION_OPEN_WEBUI_CLIENT_ID: ENC[AES256_GCM,data:l4n3e/MENfsbml7Fl0zAazBmsLtkXSFCKsDpIHjFk95+/8Vsev9qdw==,iv:t2EZeva2tOnTPZLI/J4PEbJQalrYzj/vJkLcE7nrHkQ=,tag:dUzbOghIz5n+g3Xr8srkaQ==,type:str]
    APPLICATION_OPEN_WEBUI_CLIENT_SECRET: ENC[AES256_GCM,data:hCyo8Z1CPAb6/0YkADvoju+UGGWt2HUam/AtOUd+tbeCOyW+/zdtORRNatqEpcbd8LPHZV2HdunhoyLS8mzsN/ZEo5aN102iBZS1g4HMLtRXMqb/wb+x2hxCjkkfGj9qXyEJCKQBwsmfu+2X9abJaI6WmX6aza4h1i8M1bI/eog=,iv:ilSKnLeBp/r4H3lRaGrmlDhR77ufIotAI4qp4nfpsNA=,tag:BmJRrxB4bGJ0dlMzDGeuqg==,type:str]
    #ENC[AES256_GCM,data:1EMWmlr2BD6432AjqdI=,iv:SRSNj81PsVPx4V2q69CJ+/6xBxdqD5AUzHHTSxpW/38=,tag:eNxpgVPEqfVCh2VTTE+LXg==,type:comment]
    AUTHENTIK_DEFAULT_USER_CHANGE_NAME: ENC[AES256_GCM,data:U1hmFg==,iv:rHYpOjLkLo8MJYFy2c4SkU+wVUQoXG2obkInPRIfdp0=,tag:j6vI2zoPWiAq+ljOjABmvg==,type:str]
    AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL: ENC[AES256_GCM,data:hKAFvA==,iv:TIbTJ5VDGaz7sZl4lR7Pz4QZNvYhuMwX/sv9sw2oj9s=,tag:fKQ7Zofd83Anin228HnUPw==,type:str]
    #ENC[AES256_GCM,data:u/X2CHGZJ98X4QkLkWGREYsM1mLMyo4VQdKlnZamtnI+OhNcfMqXn8F1LHs=,iv:04naP5qdihXjeSG49bOjICISTtkGEMjg3gba+IDXG5Y=,tag:23e9WIY3xCzip4gh0Dahlw==,type:comment]
    AUTHENTIK_AVATARS: ENC[AES256_GCM,data:wJxin+K8W6KBdz5HF00mujgd3lFqdVpJ3Dg=,iv:o5dAHHVYS4xgHo1YPC2Vg7xTtCTjfXFC+amqNsR5Ui0=,tag:idNM8DUVXTvFBC8EXbnWog==,type:str]
    #ENC[AES256_GCM,data:rQeZizgONFttg8HVYtToxxrU9v4I1bKky8M/lCwNWtPwjx5c9wKvAg4JPnkXuCH4SzA=,iv:DspyEeQl93RcvaAo4gwQpMhp2ltbfbJVlURCRrk3Eb0=,tag:zRIDJ+8V7xqVzXtR+8Fzvw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:RUWpEm6yiFUNKGWzOBU/OwyR1lHZdAoupTkWBS49tPs0LBWVwa0hrsPi0cbf9s11S6qXlV0jgMoRQY0hakx5+7XePuZMHAyLkVcCGoz6zTiQp9F9QgPlJl6LSxlnaGNICC/bW404aJhyf7NQhPmhyoV0tGoVJW3TEdPMei5XzR3FGr9HDrc/ZuQHgNIQg/hTl+TC7WPIEJ9aC5sAD9xRWtGg84IOUdNpsNf28JWD9XE9eUhI0tkbc2puGqWTK4f7Xor/bps+bZSOuoAOBlvrrcHvOo3l4t9dyT2MRmie8ciHZCUIVb4hT79GHDveomF7py83XOoXTkA8ecjszxl0W2DhM5roxRm0lUI6/GCd+YNSXe2pP6b8EYJoedyajeH705zd7nnn8oeURLzqy/n/xIa1L1no6wQt8biw7IM37C943diHzoLsgtAF5+/m8kk=,iv:Nh9suX08Lg0qYX+1IXiJitZ9wJuD5SzPytlEB3hHnZE=,tag:fogAhl/N7q8uoCrn03/VnQ==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1F1V2tZcU9CQ2FhbGxD
            bE00MkFFMjRTdnJLa0hTK3Fvbm4zQTBvUFJvCm1KV0VUWTJwRVJNVDdJVm1LcmxK
            V2F5NjVhTENMWHQ5aG9UbExXUllRaXMKLS0tIFpNRS9aeDFiM2RmNEpWOGF0UmR4
            bUMxOHplUGFXT3BtemlIVE9LRHVnTm8KWJgz3DlIOdtv+TXgkIsCySqiNPe9NjVC
            bzlLj35l/roIE/VwrsreOwXqpwQP+siOFGbwA7ZmQ23equKvoG8I4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:50:21Z"
    mac: ENC[AES256_GCM,data:3lsIM3bYpPXbeH8o5vFp0xXqd/5ws3tnkSs2bCHgW2/LxtLkia34BeUrUG1FvKvhQL/Gix6E7sL3nVbNSBI7qvLgnoOHn0g6VEKCyc5xCaUlph1JJDs9hY6hcclCJ937VVcu5YGtGGbqUkDe+8JfRdXvoltNVP1nJsTKhHRSYss=,iv:3kK7NFLjlCf1y/QVb0KIw1v7OfIpiGZ0VUgEynLYq8g=,tag:DjumKLRu38GkLgShmsXqBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
