apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hytale
spec:
  replicas: 1 # NEVER SET THIS HIGHER THAN 1
  serviceName: hytale
  selector:
    matchLabels:
      app: hytale
  template:
    metadata:
      labels:
        app: hytale
    spec:
      containers:
        - name: hytale
          image: indifferentbroccoli/hytale-server-docker
          envFrom:
            - configMapRef:
                name: hytale
                optional: false
          ports:
            - name: hytale
              containerPort: 5520
              protocol: UDP
          volumeMounts:
            - mountPath: /home/hytale/server-backups
              subPath: /backups
              name: hytale
            - mountPath: /home/hytale/server-files
              subPath: /server
              name: hytale
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "7Gi"
              cpu: "2000m"
  volumeClaimTemplates:
    - metadata:
        name: hytale
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn
