apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      minecraft:
        port: 25565
        expose:
          default: true
        exposedPort: 25565
        protocol: TCP
      hytale:
        port: 5520
        expose:
          default: true
        exposedPort: 5520
        protocol: UDP
      wireguard:
        port: 51820
        expose:
          default: true
        exposedPort: 51820
        protocol: UDP
