apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: teamspeak6
spec:
  entryPoints:
    - teamspeak6-voice
  routes:
    - services:
        - name: teamspeak6
          port: voice
