apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.12.1
  interval: 24h0m0s
  values:
    longhornUI:
      replicas: 1
    persistence:
      # single node cluster, drive failure will cause data loss anyway, so no need to have more than 1 replica :/
      defaultClassReplicaCount: 1

