namespace: synapse

resources:
  - postgresql.helm-release.yaml
  - postgresql.helm-repository.yaml
  - postgresql-credentials.secret.yaml
  - synapse.helm-release.yaml
  - synapse.helm-repository.yaml
  - synapse.namespace.yaml
