apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgresql
      version: "18.5.14"
  interval: 24h0m0s
  values:
    global:
      postgresql:
        auth:
          existingSecret: "postgresql-credentials"
          secretKeys:
            adminPasswordKey: "admin-password"
            userPasswordKey: "user-password"
            replicationPasswordKey: "replication-password"
    auth:
      database: synapse
      username: synapse
    primary:
      # Resource allocation
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 2Gi
          cpu: 2000m

      # Persistent storage
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 50Gi
        # Access mode
        accessModes:
          - ReadWriteOnce

      initdb:
        scripts:
          synapse_account.sql: |
            CREATE DATABASE synapse_account WITH OWNER synapse;

