apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:ZmdwIhk6pSgxQRYfdABfRt1+7Pqrg5i1Yy0o8AcwqSUd3m8cj13rRk7CB9I=,iv:/9lv/iIvOvv4725EucCqqafFKa5o+NvDwlmfPgwb+RY=,tag:asQDk5HRRGRsp2JF1gUSQA==,type:str]
    user-password: ENC[AES256_GCM,data:D8crUlPxaHhGMp81MoS3pbOt+Ssg+vXHAixvs6KB7jvb21ZFHEFcU7z0JsA=,iv:zbkn/nFI557oQrLOg+lf9nml9d6zkjFxHYAih300NU4=,tag:ap4vg5+wqKbp+LilOpBwlw==,type:str]
    replication-password: ENC[AES256_GCM,data:5h77vnnBXwlZdpKqj8Djo9N39AseBrRsWnNEHaNs4N0KyvKg4RU2eKI7k2Q=,iv:JbPrqVPQptRfyLU359rSiZ7g4Tlj43lwiV1Zl+OLtuQ=,tag:J+RiSdmKPcAJlfzUCtoWYg==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d1UwYTAwOEFvR2ZZSjZK
            Mmg2SHdNcjZDQXIvUHV2RVVoRDBCdmVLM3lFCkYzeDJ4aExTSS82WmxVblpvMjdh
            OHl0N0RkN3U4Z2dGWG4rYXlBWkkzOHcKLS0tIEFnYys1cGRhQlEwKzU3c3BZaDNO
            MjZCNmZwZFA5cnZuNS9GbkxWY0JoenMKnxJa9V0muiC5JGAzzg/uYayzrEmJaKv/
            V0wm0uXj7MULmXGQ6fT3TY7Xm0Pwc90LRsrJPAQ2yve3/nhyu+g1lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T23:31:46Z"
    mac: ENC[AES256_GCM,data:v9WArq/EaPlJfQR7O0ohCRDs+EOABbrTDPi+lh5jrxKSZ9YZ07/R+g+5PTNlpT78yJQJN/05N95oxgwO79JGoaUQZglCG2ul77aEgfhak//uniqWpsiBCPtqXO5mwcmiTIrRosjWFkXuptjqAN4GvI97Ams6WE4E+Yg6umAML4Q=,iv:BwMCsX8m2+6v3X/djnH8U2vddnKs8+LMR5SyF5WYu2M=,tag:NxA6GgyZAlx36gxt6sE+BQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
