apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
spec:
  chart:
    spec:
      chart: matrix-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: synapse
      version: "26.3.1"
  interval: 24h0m0s
  values:
    serverName: canceled.cc

    # added to all
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

    elementAdmin:
      ingress:
        host: admin.matrix.canceled.cc
    elementWeb:
      ingress:
        host: chat.canceled.cc
    matrixRTC:
      ingress:
        host: mrtc.matrix.canceled.cc
    matrixAuthenticationService:
      ingress:
        host: account.matrix.canceled.cc
      postgres:
        host: postgresql.synapse.svc.cluster.local
        port: 5432
        user: synapse
        password:
          secret: "postgresql-credentials"
          secretKey: "user-password"
        database: synapse_account
        sslMode: prefer
    wellKnownDelegation:
      baseDomainRedirect:
        enabled: false
    synapse:
      ingress:
        host: matrix.canceled.cc
      postgres:
        host: postgresql.synapse.svc.cluster.local
        port: 5432
        user: synapse
        password:
          secret: "postgresql-credentials"
          secretKey: "user-password"
        database: synapse
        sslMode: prefer

    # disable build-in postgresql
    postgres:
      enabled: false
