apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  admin-password: "WEii2bTgAk/ajS6+glUDb9OBh1RIBMFVxNRo0dgZQ80="
  user-password: "vcZ8XIgfIHSJVPCX6Kb3w5x9aHMHqYY5yg6XECTAGLI="
  replication-password: "aaBhNoPuUcF3Ab0+PUg7MyVLGYKO6ML7hl9P9wvkjWw="
