apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth-cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:SPFFwhCVGsnGSAal97FtQtaTQppxsofX4lgNpZLiZSQZclTMVr7Mzw==,iv:lPDrUqv24x02r5ES0yOWtO2N+bfigh10gyOoMPnfOBg=,tag:AJKnvDDFSgZC2TfRaqxV2w==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGdoNzBQWW96RnVKUlUv
            RitOSXBzSFYrS2cyZzErMzhoZXlwc25UV0cwCithYUZCYVI4QmdsRUdFQlo5eTlX
            M0I5bEdOS2JSeU9uWUcxcDhhc3hPVFEKLS0tIE1rbVVzL2JDRjhzcHhXaHoxSlor
            c3VKKy9iOExrbzUrNFNaRTQ1YjMzSEUKeEVeqqjajJfITTarTHqL7x0yKh6cUs+T
            2D67AXc+/RpG+cmq64IVIJgJ0RGEMb/SnVKmhYc3zj7y5ZBv1mHLSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:28:06Z"
    mac: ENC[AES256_GCM,data:WYYnpG3yqQjHtZZRZ/dXI3Ts/EsDoc0FdfoHnPp7ceKeyrVs0HsPCyPXwj4vjWT8qZQzlmyvYfcujHvjDEcZ46FI+GCyW/7oUfvJjnHy9JNnH+sV40q22JV7NffpkOry4ZrTpExFw/161ytMAWCi3Xg0wkriS0e0XMPUuIvcXxE=,iv:6xlRFeW8wjgsaKtHG830AqoU2XQdG6KTMhPaRdTotiY=,tag:uzYMTaoJe5VG+q7g/amiFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
