apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth-cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pIBqBdOWqCjkMf9mlrA/4a6kgWEIVTRZNgHUFh4HscXIu3SicASyIA==,iv:JcQ0sbqZPIFm5kgkaGzfm2dU6K5hnvXBlFNbHW3Gw2U=,tag:VZVJmwIU2XgASNtjbz91yg==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGdoNzBQWW96RnVKUlUv
            RitOSXBzSFYrS2cyZzErMzhoZXlwc25UV0cwCithYUZCYVI4QmdsRUdFQlo5eTlX
            M0I5bEdOS2JSeU9uWUcxcDhhc3hPVFEKLS0tIE1rbVVzL2JDRjhzcHhXaHoxSlor
            c3VKKy9iOExrbzUrNFNaRTQ1YjMzSEUKeEVeqqjajJfITTarTHqL7x0yKh6cUs+T
            2D67AXc+/RpG+cmq64IVIJgJ0RGEMb/SnVKmhYc3zj7y5ZBv1mHLSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T00:38:23Z"
    mac: ENC[AES256_GCM,data:ZRphKv2RABbxund7vIuAaBhZ0zF6d0GS1KC0aVzkDew+7X+7y6iZ6oNrzgDIrZSKQi9lAgsdFvpndJxoWlIbTJJMshZycmyfL39r954i1Rl0Emh4OeXk4F5/ysKxII6HK2V3wpIBSgS/QW7xyGoVfauqD7ChfN+ZR2jHtUutkzs=,iv:A8RJ8m22c+x3gv/khOStWitmPoEu1lnYD6hifJfBdsY=,tag:KQ7hwZJc4yRl540hhBQLpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
