apiVersion: v1
kind: Secret
metadata:
    name: wg-easy
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:e//vXL8=,iv:a9ZciwWDBNEiPSBDB5tiNl6ey1zQz4XKpnvMJs+6CgA=,tag:pb1sB45dZw+IXEegCf53JA==,type:str]
    password: ENC[AES256_GCM,data:aYhq4X8=,iv:FvLnUG97Dl1nBBI74aMMQkpaFhW9KMRnwCqgciQW3YY=,tag:HzhmRIO8+E429RKZecIQiQ==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNytNSkNYaG5MMjdjZGU4
            dkFjaWxOd3BMcE1TTm40M2NHMlZLZm5NSkVjClQ3bEIvYnFxWlNMQmNaL2pwSnc0
            QkJwQk9oN0s0WXdUVVB1QW9BZHgyTkkKLS0tIFdZemh6d21hcFc0USt6NlZnWldk
            ZHh5bDhmbUpnVDJoN1JSLzNxcGc0UGMKpsT5RROCQLovmNRklTZORObfdrQkW4QV
            q+WOHdA4Iuh52L10lk8SydPWyqvf0u9+v7FAQDXqKZTvgtTeVNtNJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T22:44:02Z"
    mac: ENC[AES256_GCM,data:0ULqxu4qkx6GHYnABnr1PA1Wz80hpSetD0Llh8UXaMsiFLS49FtE/Jp78DZv9Uovy/AYeDfr2eF+YmTXmedq14FRvtC5SyRrxCfVPR/BuVhHZfGTfv+B21/qImyM7rVr2UZGrKuCiTm3y+jiUkgRB2F1HKkzsYVHA0weyzhR9k8=,iv:bqpzb3aGE//o+6hIznjjfHT/0dDoCfziFfmYIZ2i6hg=,tag:OkiTLqeSP1ItGiuMD7ZXtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
