apiVersion: v1
kind: Secret
metadata:
    name: wg-easy
type: Opaque
stringData:
    INIT_USERNAME: ENC[AES256_GCM,data:Y4klDBqDicQ=,iv:uHl+yJvrWfi3JWsppISeGjimC1Gh6oMjxO/R2xvkvwk=,tag:FKb58FPYIcFORcfPcYoobg==,type:str]
    INIT_PASSWORD: ENC[AES256_GCM,data:42SKzGK/bgxItaamr/jRtrEsSNMzic+v1D6oGdEt/dbp,iv:XB/3EeUi2VfDqWcoy5MJIGYcxrWqCMSaNCM/WUikMIc=,tag:/mu1359m3HsTBotpkjEFBA==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QndvcVFDZ1hDWm5iVVgx
            S2wxZFdMOHBnckJ3T2dvZkxrL2ZpbjNUTVRJCnE0d2lWN0VOMlJ3cmIrM2hSSGJ0
            V0xzd3lVUmpmeUFQdjgvVHNiQW40Y2sKLS0tIDhnaDcvT3R2YldaRG5nbmhJN3Mr
            MitobUF6UzVPcE1UTjBoTTdIL3p4RUkKbtaBoB/+BJlBelqxZWve8A8XJvZO/aBW
            9rKS4UIUDDs7LSndzi/lYG8JbM6n537ikm9TeMKWu/khs1g5xYJmhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T22:08:05Z"
    mac: ENC[AES256_GCM,data:11dyWYeoegccb4uejh2YdWA3jTzevFXLmwKADMJe9TqcMM7NCjsU+kyhlFNIUfIS1u+B1cq+Mx8BRe9ZSbqR4HtRsGnp6uXRIWUcJOeYCgQb9iTL63a5l+GF7y1cfCXmQfvwTnbglAnjSTlbPhOFNJOw4jhKGaEQnJkt1MjjZAo=,iv:GJGy3oWwdbGx2t+uUOAWdpQY0X330mxxFRqzYKvyvOk=,tag:gg1+Je+Ap5VlbZMBLg0KAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
