apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy
  labels:
    name: wg-easy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      # see: https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Kubernetes#add-persistent-volume-claim
      storage: 256Mi
