apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wg-easy
spec:
  entryPoints:
    - wireguard
  routes:
    - match: Host(`a1flex-server1.oracle.cluster.parzival.space`)
      kind: Rule
      services:
        - name: wg-easy
          port: wireguard
