apiVersion: v1
kind: Secret
metadata:
    name: wg-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:e//vXL8=,iv:a9ZciwWDBNEiPSBDB5tiNl6ey1zQz4XKpnvMJs+6CgA=,tag:pb1sB45dZw+IXEegCf53JA==,type:str]
    password: ENC[AES256_GCM,data:aYhq4X8=,iv:FvLnUG97Dl1nBBI74aMMQkpaFhW9KMRnwCqgciQW3YY=,tag:HzhmRIO8+E429RKZecIQiQ==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNytNSkNYaG5MMjdjZGU4
            dkFjaWxOd3BMcE1TTm40M2NHMlZLZm5NSkVjClQ3bEIvYnFxWlNMQmNaL2pwSnc0
            QkJwQk9oN0s0WXdUVVB1QW9BZHgyTkkKLS0tIFdZemh6d21hcFc0USt6NlZnWldk
            ZHh5bDhmbUpnVDJoN1JSLzNxcGc0UGMKpsT5RROCQLovmNRklTZORObfdrQkW4QV
            q+WOHdA4Iuh52L10lk8SydPWyqvf0u9+v7FAQDXqKZTvgtTeVNtNJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:12:42Z"
    mac: ENC[AES256_GCM,data:dUO+5gWpw82HO/u2pQXfQNn42w8/p9OVaZ/V1iG6GX/+44+4v/CGh2vXapD895yf/qKQqMCKrJzewmN2i7KdqCHPWflnvVX+uWx/G2SrHtC4+gPEWRro10F2ObXUcJkB7q8xNqyPH7N6IpVzYrhEkZLJQn+zd4EhTfzgPbUg1Po=,iv:vHFn6VMdsCRS2zMh2VO6PhB9ofn7caVjdPh+Q1t0QIQ=,tag:W/jEPA6dgxg4elTn2wLE5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
