apiVersion: v1
kind: Secret
metadata:
    name: wg-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:e//vXL8=,iv:a9ZciwWDBNEiPSBDB5tiNl6ey1zQz4XKpnvMJs+6CgA=,tag:pb1sB45dZw+IXEegCf53JA==,type:str]
    password: ENC[AES256_GCM,data:CuxrvHgfCxa7/6nX,iv:e4+Wb7YZisfWcAPqW4F+xz/lDAfbIkB8Wi/Fwp82yPk=,tag:Sa6MdoqQbbfpvjCsaBaOeA==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNytNSkNYaG5MMjdjZGU4
            dkFjaWxOd3BMcE1TTm40M2NHMlZLZm5NSkVjClQ3bEIvYnFxWlNMQmNaL2pwSnc0
            QkJwQk9oN0s0WXdUVVB1QW9BZHgyTkkKLS0tIFdZemh6d21hcFc0USt6NlZnWldk
            ZHh5bDhmbUpnVDJoN1JSLzNxcGc0UGMKpsT5RROCQLovmNRklTZORObfdrQkW4QV
            q+WOHdA4Iuh52L10lk8SydPWyqvf0u9+v7FAQDXqKZTvgtTeVNtNJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T15:33:34Z"
    mac: ENC[AES256_GCM,data:rJZQutv0Y0Q3xtx5T3U7K2lf+irCxQeu+CEtsowov98+l5XgUnjCN+j5Uqg48Qc9q7ACmjasAHAdP29dgtcEcIiZs9+LueLkWSjMnQKzaULJPYFv1+ioGGwCmwSboy7RvYkB8Z8KulwYG+l2FGDllyRZBwUjW/7OsUsrWlRprL0=,iv:Yb44Om+89emg6hqa7/3/eepowneuOf9VKEX+uVSjRho=,tag:7/Ws3sUEkMXxf1t8EhrXLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
