apiVersion: v1
kind: ConfigMap
metadata:
  name: hytale
data:
  SERVER_NAME: "Hytale Server"
  MAX_PLAYERS: "20"
  VIEW_DISTANCE: "12"

  AUTH_MODE: "authenticated"
  PATCHLINE: "release"
  DOWNLOAD_ON_START: "true"

  ENABLE_BACKUPS: "false"
  BACKUP_FREQUENCY: "30"
  BACKUP_DIR: "/home/hytale/server-backups"

  DISABLE_SENTRY: "true"
  USE_AOT_CACHE: "true"

  ACCEPT_EARLY_PLUGINS: "false"

  MIN_MEMORY: "2G"
  MAX_MEMORY: "6G"
  JVM_ARGS: ""
