apiVersion: ENC[AES256_GCM,data:wio=,iv:ttVw3qCZbp8UmGbgUXvnXlbo7SruKyUUV6lf8pFL4SI=,tag:dzpbqr7UGnv4Swb3bscSqg==,type:str]
kind: ENC[AES256_GCM,data:r30cEPPo,iv:EWuZppPiNB5Rtcy5R1q5kta/8MPYF7f52DxvUXAMMRM=,tag:0PWxkHMSfDhac1hvvH4IBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M33IZ00=,iv:q+rqdSDzG/ilX7XIKHnswxDzq+Oq1fLwhUz5yBEy0OU=,tag:HntaBP530hYjIXt0Z+x9Aw==,type:str]
type: ENC[AES256_GCM,data:F8vOpWk/,iv:FhMKEBpnW71OalPvgruirii3oAgMaq6rqtyNB9F3Obg=,tag:YPn6tM2BFcR4xZEyZCf8Sw==,type:str]
stringData:
    proxy-secret: ENC[AES256_GCM,data:BVwXRO7MiNhGqzOmmltGR4AHmxBzm1CMcTCPt8V2DkH8XUrB3+snzweDwZFAlKFrDyNQyOi0ae38P/+DLu8H1g==,iv:A5em2GdWXRihVcmGDaqx5AvmPVJdzN1E3jCu4I7yf/Y=,tag:XTy4x5J8Bj+yIaUdp2jGfQ==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSjZUQUxTR3F2K1JlUGNR
            Z05PRmNNenc1VDlSdm9FUUx6OVI3S1NEQlNNCkRNbDRtUTAzSFhpdmdqRm1mclJl
            Ymw2dm0rQnkxL05VZ1RCdnE2L1UwOTgKLS0tIHc5c2JZbkYzbFhtcFdVVzlhaGth
            VzJNMFJPUzN4MFZKRjJMcGpkam91OFUKanAilP1Q3dyRA+LTv3kJzVlVk9GMZmzn
            XUdrxTNcOkEaUxaqSG3PhUwYHxwCMQvk0ed20ptFN4n9xHWUnglsZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T13:23:18Z"
    mac: ENC[AES256_GCM,data:34UED//Omev7xiR9Qcmrumoa+kpl72wfMEVhr1HyMEfl3ZmmfdjvubYfmUv2PMUQWdmluzYSW2+32+NyfB95POTryhpFKOnMr/ms89NuB35EONfyF5NPdpsAIblYHe/OhuRP5lnDGoJzaRtIIztyJvW/evbZ2RrGcb2wVdNI280=,iv:ywbIoaCgl7uOJ9U8yql9Lg+gADFp3KX+Pu9lDkP+MXk=,tag:s1q7W3fYpDbQhMU2Ct76+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
