apiVersion: v1
kind: Secret
metadata:
    name: proxy
type: Opaque
stringData:
    proxy-secret: ENC[AES256_GCM,data:/mGNZhTOoE+DeB9Xr/qu/YYaVGqkeOaBbiCC06n9AVvA1PFk+kGNwb/sJuMWe65ERUwe/RhFFRRBWKTgCWqeMg==,iv:L8KwoXy7z09NAI83gzBtKZkJAtGCGeeD4rdFasYqJKU=,tag:26u/fCMN12GJGcwOyqQVVQ==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOTYxQjAvVFJJdi85VFFP
            VEZNR1gxUEVUMkN1YjVQZWg3Y0lSeWlBbHpJCi9DWFU4dmN5Z3BaeHY1c3JuY1Fu
            UXE2MElpUGlUbllOc1BiYlNnbGlVSXMKLS0tIDB4a0FJWEJKTzg2VDdyYjFNQ2tt
            azZ4VlIyMU11dkNESXpvSnZGcDJwaUUKfqHj6RlsVUB9+5fEztM8ehkQlMGAiYsx
            7u45ZDW5Kp/CpXZL/dlJCSXcaF/e5RLiSyWsvecwJ2zT/d6V/1sDZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T14:20:35Z"
    mac: ENC[AES256_GCM,data:3aZeqxkBuyCaoOVNHF8UuuN9xomNdL7LTrGWMrUTpPz+04f2hhGVs8cMTVTOmEs2JKkc9X721r4BLI1twjYbh5juTieUsbjVj5HTTuE4kpRaAIdH07OS0cN8MIoX14MfFGQJVdaxoE7D+L5Fz8JYCG9TnCebNiEMOgi9ShT3WVc=,iv:9vMdpJwTWQUoFm5XOETKGhB+qkEHnK+wTX5r3QN9Wyc=,tag:x+eaH87IjEhxjnXavA4eDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
