apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: server-creative
spec:
  imageRepositoryRef:
    name: server-creative
  filterTags:
    pattern: '^(?P<timestamp>.*)Z$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
