apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: server-creative
spec:
  image: ghcr.io/parzival-space/sxmf-minecraft/server-creative
  interval: 5m
  secretRef:
    name: ghcr
