apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-creative
  labels:
    name: server-creative
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
