apiVersion: ENC[AES256_GCM,data:xus=,iv:C2tjScKh7lid4oRL2Cd4eYPHEwdYchK7tnVkbsD4iqs=,tag:/4mC+G0Xegu+SISyOwmTmw==,type:str]
kind: ENC[AES256_GCM,data:fOL8RFIy,iv:zoYnJMV1ETNDVvxaZHzZIg9geArAEUf5zm+IXLoPqsA=,tag:hVOjFxZphKq/Y4wvz8cHXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:27PtHQ==,iv:hCi//DkqRfOtgnOt5iw0a7MMYjhlI1ZHNI5pMioSJNM=,tag:7SZLqBtFIBU2fXhM6h3B2Q==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:y8gSpHo7JHt7vPEA6imrsMBKwbaUAbGSdQ0LDyUkX050FuR1b+UfOrlYH4Z1UoJui5/iN9+EGIAKdG+IpTzyMSuEYWfFtBBOqyYubhimcUKFB9ntSVyGhk88txZhO+XB4Rc7KP4P6g7/ezuMDOUz+Srzlo1+3VEdl5CEpNNTNXAs/DUdm8zpMbH0/Phme6H8MOxeBhkDNntVxajRWS7jyYgbp6ax+6AAkJU7Sr6xS/9RqHyN0rWM8njeJVrjkYrhhLCb8/aHdSe7OpB3DVpKDk7Gh0QLE6tQEK1GAd5jABVM1dyDWdGtQkZEO/SPqnESXofYtM9ktjiFCP/K4wFWOQ==,iv:5QoXeFwiXE+0GlPIAMnN4/rilU8PDH40N+gdcaRvPSE=,tag:psdMxrfHqUWWiFLtT7xDRw==,type:str]
type: ENC[AES256_GCM,data:itCL8Vx+iWl7ihnZixvb7GjxWFTTSrPWRbd0Ji0R,iv:GS6q0/bVuvzf4bEDgmh1InMXpp7n0d5ZujWtqf5HmgU=,tag:eP/EAM+OSoLM0ScZHaXMnw==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMFRVYTNsbGRGLzdLcm12
            SWt2cUErY05YYks5QlBKOGRhb3JqRlVUVGwwClBLQTZ1c1VDU29xd0JEa2c1OWVF
            WnlyRXI5SE8vYnAzejRCcW5RSUh0M0kKLS0tIDJma0hjdkVDVVoyUzR1d1NSNkpE
            cHhCSEV0WUFIMmpuZGExdWQveXZYVUkKylZlpmsR6s9KNLdP4Iy6QhbN6zc2chlG
            Nt0rH8+DCzet3INzNYMlH9jUWr0EiPE6gy1WVxo21+7E3AznYHgz8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T13:18:41Z"
    mac: ENC[AES256_GCM,data:CEhmU+GDQsE/aOUBAmDuZkYfCwjDU3SoNHvoTI029nL/PUahrUcfDDTbXmuxc3YQGTXvIVyr1TxUiDhC4a2+5KNKec3HoapOOtGWVSigQBcbTV2d0HbIilACAPYqk/pkjTVtN1Zcuw9X7QUY3EicKvJ8IWVqbPzqB07kFUU9yP0=,iv:nSCepLjr/K3H3Kc83E6u8iqfotozboSTQxmHM6XnEwI=,tag:9REHzkBqF8vfo3ygumsY/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
