apiVersion: v1
kind: Secret
metadata:
    name: ghcr
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VfKzjbMPQES8Q5KFMaXmFACou8fVew//1ZQoZ9Wqi8Opan3Kw9UovMQF7qmVKc3gJKIxlxsigzMN/3naNTaq8qXjHyBsM1+WNZz9GB1ZWLzhPuvaY8iuuhGpvBnSOarSTqkA+Vx7wZ0YvCpBJJRKeyLuvHmIFJQ8A143ZdVhoYj2w0QiNEqAp+pPjav7vUfAV8l6kk6/XriCJnjnsKa9Mo4NrrMH4xuEXjlVoI8CNBTQaCebmDSmKeMVo8TbzprYAqiNzycalSSUuCI6cY1Ht4pShWh9L6JCl19+6KfZCsfuDozRnD3n85k+ssYVnhvw0Bm3PhRU7q0GsmUDrx6amA==,iv:gbk2Sawvp8IrRUIomlbOMXQbWZBtyCpY/Xak8ZG/4n8=,tag:vDidvsuUAB3dGM90qMKUNQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK3hGOEI2THdZMnBGWjNR
            dzRGUXptNWx0MG5LNHQrR2ZMYTZ4dWJ5blRFClhaR0F2eXByMXIzKzRpWjFVdjBO
            RUpSdkV0eUFLaFE3dzAzN1dFNWNmd2MKLS0tIDJyVy8zSGZTKzRPSDVudFhIeVV6
            b01vcnBFNTdieHFySlhtRE1VVWFwaGsKaQIxJveXcUdN2Izy1loatE4QPsaeXCJf
            6L0d9hiRkZFM82FNtiZvrlU787uyTvfIMgrkOYNYD1XjB2yXmJ2Z0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T14:13:25Z"
    mac: ENC[AES256_GCM,data:AFrJlp0C7UjnOWbw9GAHwKYojLSfBAD+0SI6ThFySwY2BlNfmKLMJOJxSmh1SrUKbpog/ZaMKG6/H/3XPqQwXwsF/9LCDnRla9dIa5sBuFUGeTTLTXpFygfzu6hBFDfUpiaRAhxSrwyfh3Lh6+oJyi2/jxG0wrqq4eqlDszVPWg=,iv:Mu1WvTGI74a3rO36qM2PzbToNhUSsPdkq+2os5gYrGY=,tag:u+aWSTw/6sgzQh2TZEq5OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
