apiVersion: ENC[AES256_GCM,data:DnM=,iv:Ztp5X5lGHvp0B2SKZAHQ9SEgVBG0JPegSsk4TC2Q4aE=,tag:l+Hl9ujxMTG6i2gjDaTE4w==,type:str]
kind: ENC[AES256_GCM,data:5Ab9h11t,iv:DiPZv1oq5j2DgjWt3v0D/RUy6RuBSGAlM32wRo9mdaM=,tag:FCWUXgXcpYguqEypnyjcsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lE2MFa9ftApfw1iw0Qxp7+QmZg==,iv:S47ZaQx3S7YbTwSyX0sdSm4V0XyO3RGqsbRSq+P/06k=,tag:A/wgSt0Gp5yFabfs1MKUtQ==,type:str]
    namespace: ENC[AES256_GCM,data:6fKp+M411vePcTcWkg4=,iv:fbkpHTTx5wtkk9AY+cqLUXnfVJck41AEM+dTrMl+pts=,tag:BlU4W8tUEE4Pz6o4zXfVRg==,type:str]
stringData:
    identity: ENC[AES256_GCM,data:IRBNqHf+Tjda2WW8e74l0Ss97iYK+6hGWBnhggMFwgbSP1B23p9EPgCVODy5XjotF8bb1o9Byol8HgaMil6KCqiIqT+Cv4RgtbtGDeNxjZaT9iOgTDzoQR6Xj+y4IuWR4Crt/q9xPB5jry1S3uEEjjjf6Qabpb4bSr+5+E2I5nfYJTKDgkDqAv3fmX2XQx7foq5N7TYjyjveWmm1/o2Jm51SY5UdA/DbNcF6bv2GXLBhnj09IpRpxdIbM0n4oCj6UZBIhXbvp7G72I9Mr+GtQjv6/ueHG+YC10uh+rjXJUswsDtVqApf5lFX5y4pcQnKoxIaZAWyUaFdVdCs3xT8xo7iRsp/TgA1Yo+UrY6iMk5vtAnKx0yHidrWRASWph/FEJ8WLqgc7QhdEtRBRinbqNqfJGF2v2k0uy8REUNruzpL2Jb3W2gaUI7GZi6AbU4g+lGTetEDv4EZBULvd8nvMFaBOMigNrhErecRL81dDZvhaIqFzN/vyOMbUhypMTvptSOoHLGHSHGHqtILYIOh7ebuAm+EyuuN3UYC,iv:5691kzNLEYu2Yz6d89Ue7O208pe9jIKNOZPefuvp4FI=,tag:2ck4Yr58WXl/A0QnJospFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6ksacuxDgXSq+MI0jo/t/q4NJzuMR6uYVMi8pI1lncELKDL2mGnCiAblF4K2CljCEhr8svCvBO7FVW4ibIiGi6tMdyO1b8td1gcHJYsXXNb1,iv:h5rWrlAvqXtiTXxN22OOMvU9DcsixuGRcO54aCkCyfU=,tag:nycUesq2eB+cZsvuimoXdg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Bxyds1ea2P8JloiMdT1oo9hI4mJjRMQ6XW4i1xoY0DFFMyXbil4mMdsBMt8YXQW+ojPvXVryvNS/HerOka0gTtuzhyU4Ykbws8PtxhOlnae/zVXMLkhizZVlWoNxkQNvT7bVSHINu9/TNSjYUmIXnP5memU6l7kK8gao0k2hOK+th0H8Tx+7DKmFztf3JBbU9D/HnSv7yO3ZwD2JiAdJuxBGQZBeBQFTupt1,iv:T4uiEEXrrbsGPRXv+9uRIETau8+8xdw6CaCznL03UbE=,tag:ZgAFUwjCnPt86oT5PnxKXA==,type:str]
sops:
    age:
        - recipient: age1tyjaypk0xxzs4p7lecvdsxnsh0223d2jdq5dny2prjkgyzwn74eq08uqat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZm93blBBTGV0M3FEb250
            UU41WDdha3VkcjFIamgyQUZnVllUbGVjUm1BCjVoT0JTRVluUjVtdjZESjN3blls
            RnVkc25YT0g4UURaWHl2QXNkT2Rsd28KLS0tIDdMSENhZ1RqUFVjNzI3N09ncWRB
            ejREMjVmaVpHWXptTWpJc2NrWStTWU0K6I3PH4UqAd3sr6AswN3zOT2D4hflRePk
            UkWZq0l+gmTMSRnUGYJ7sYXdeAcTeWrZSUVtvNt+QXbwDH8krxGO+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T03:18:06Z"
    mac: ENC[AES256_GCM,data:qHjy9KE8SJKYhM+2FSPUx+LAYXjZLvBohjI9S15FeRlT7SkOwLrOgbj1Fh/sSlpxq82OuNwHLPcs8pxuIrzuf38mBgNu5yFzqvkxVMKC4Eh7y4SyVAs2GsdNS/aP02RZ+qHZk/X2HQ8oSH8J+/PWQtxAViEgcUWuTgucMPEKFaA=,iv:8UcD6FeKzwBOatzviXB4nBKwGt2HaYCsJ8Xl91v6oLs=,tag:HhLdNG7Ze8bBgS6mwq+b8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
