apiVersion: v1
kind: Secret
metadata:
    name: pg-admin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:vt2WbwV06gvJ6Yyym5F5gXM=,iv:Y+HKZxTcMRrSAoo/EOof1lxbbM5P7sgxJR8gs0fk/cQ=,tag:vL2k9smR8QWBbKQlotda0Q==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:AwfN2Js=,iv:2FupskFJvyw2V6OhHbCMFYUkxWD6BnVEOVixXhuBciI=,tag:LWlHbU2vTOpO2vquJD6zIg==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbXZ0TzZWQ2RtZGYyQXFQ
            TnJqUi92a2tZOEtsTXNnUGRIQ2tqZEVzeVRFCmd4anY4eGNUbU5JaDZtOG1pM0o0
            dklaZ2toWjB2VmZGSGV4MUI4SVF2VzAKLS0tICtQUWZrM0hzTEppZFlXS0szcVVF
            TS9BN0V1N3JEbjJ2ZGQ2VGFpdmE4MGMKDcAmDELnnd4YuEVixZpxL101J1byv+E3
            SNMntsSf+oFD0garSeQh8riqCOJlE0Eo5GhxYsqNg/9112sde++v4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T00:40:41Z"
    mac: ENC[AES256_GCM,data:D3LZrJv4ufohlMclDBOLpdT2ciV/19Fgxdco7asOeqMEP0lTEXNvscN5MsHvCDfQrDJz99KWhQWBaaAjK/rPrw3eS3Ri7CZyQB99BxF/k8XJhegmfHyheYCBN0ZS3xccohC/GQzZVMtBqYcqJ3CU/KmP0QO/05cOS6s/pvvdP7I=,iv:kOb95FR0YcFY7DZGv31HzhTiyhBVcYMixo/sgO5EIEo=,tag:7opKtPrJ2hAgR6p17TWXeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
