apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-admin
spec:
  replicas: 1
  serviceName: pg-admin
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
        - name: pg-admin
          image: dpage/pgadmin4:9.13.0
          restartPolicy: Always
          ports:
            - containerPort: 5050
              protocol: TCP
              name: web
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: data
          envFrom:
            - configMapRef:
                name: pg-admin
            - secretRef:
                name: pg-admin
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

