apiVersion: v1
kind: Secret
metadata:
    name: pg-admin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:UDlN2ESwtdlDQiFu5hog,iv:SHd97d7PhPkGf6HfKq58Bsch1RoQL2rd7deE3P0DS1M=,tag:9YLFMq8VP/niwOqXUc9wHQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:AwfN2Js=,iv:2FupskFJvyw2V6OhHbCMFYUkxWD6BnVEOVixXhuBciI=,tag:LWlHbU2vTOpO2vquJD6zIg==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbXZ0TzZWQ2RtZGYyQXFQ
            TnJqUi92a2tZOEtsTXNnUGRIQ2tqZEVzeVRFCmd4anY4eGNUbU5JaDZtOG1pM0o0
            dklaZ2toWjB2VmZGSGV4MUI4SVF2VzAKLS0tICtQUWZrM0hzTEppZFlXS0szcVVF
            TS9BN0V1N3JEbjJ2ZGQ2VGFpdmE4MGMKDcAmDELnnd4YuEVixZpxL101J1byv+E3
            SNMntsSf+oFD0garSeQh8riqCOJlE0Eo5GhxYsqNg/9112sde++v4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T00:30:58Z"
    mac: ENC[AES256_GCM,data:iVWLARV1ihRAbZbWpURFyFbkKKSfk4BMLwA13oKqTPLwSU9uIOjrUdvsm4I7yrmEIkyiISE9sSc+Z8ZGp1AcKKEZr6lTOEjkT7xWdlu/LKeT1Dmg+6xiLh2PFK6i7VfL4xJFfnK2E8hGbD58OtoQDDtct4+S9B85hC0+FHqEbm4=,iv:ks/10o4Yhh1I69Z4iAIlUqj0SNK2sAarVgRVBq4vw7o=,tag:Lu0/Cg36lX5/zbgkE3eqtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
