apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-admin
data:
  # If left unset, a Postfix server will be started to deliver password reset emails.
  PGADMIN_DISABLE_POSTFIX: "true"

  PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
  PGADMIN_LISTEN_PORT: "80"
