apiVersion: v1
kind: Secret
metadata:
    name: pg-admin
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:kjzPJrCZkqOFT38s0vT2PiZJsMhqT+1alINV/yXiSNvVeVQH+YOxMHrgey+yRH8h,iv:O2qR2WltLR0Ze9cnClsFfBV8XsiUTEL5K2i2pW4xbyE=,tag:TYrSLMhVcKOYrMywWeKAgg==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbXZ0TzZWQ2RtZGYyQXFQ
            TnJqUi92a2tZOEtsTXNnUGRIQ2tqZEVzeVRFCmd4anY4eGNUbU5JaDZtOG1pM0o0
            dklaZ2toWjB2VmZGSGV4MUI4SVF2VzAKLS0tICtQUWZrM0hzTEppZFlXS0szcVVF
            TS9BN0V1N3JEbjJ2ZGQ2VGFpdmE4MGMKDcAmDELnnd4YuEVixZpxL101J1byv+E3
            SNMntsSf+oFD0garSeQh8riqCOJlE0Eo5GhxYsqNg/9112sde++v4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T08:35:10Z"
    mac: ENC[AES256_GCM,data:hsRZb/VfGUOmkHeOGmZt2VFqxwAjDJttxOCsm8yhsM8wTO3m7ENnA5vKvMgfNSC408wkQPmfM7i+oHVUZ9vznzxytEOkLuqtLRQa5dofpKReBalIXhHsemz6F0mrDSsmC1BD62s+1gQWTp4moIoOKwFVUM8M1r4kDzJ1qcFoNOM=,iv:DKgqQ434oRWBaX2qT+yTB4rGsGcQj4dG1rx4dayygcw=,tag:ZHjFPrwIcDxR4mVcbD/E7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
