apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-stack
spec:
  chart:
    spec:
      chart: matrix-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: matrix-stack
      version: "26.3.1"
  interval: 24h0m0s
  values:
    serverName: canceled.cc

    # added to all
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

    matrixRTC:
      ingress:
        host: mrtc.matrix.canceled.cc

    elementAdmin:
      ingress:
        host: admin.matrix.canceled.cc

    elementWeb:
      ingress:
        host: chat.canceled.cc

    matrixAuthenticationService:
      ingress:
        host: account.matrix.canceled.cc
      postgres:
        host: matrix-stack-rw.matrix-stack.svc.cluster.local
        port: 5432
        user: matrix-stack
        password:
          secret: matrix-stack-app
          secretKey: password
        database: matrix_authentication_service
        sslMode: prefer

    wellKnownDelegation:
      baseDomainRedirect:
        enabled: false

    synapse:
      ingress:
        host: matrix.canceled.cc
      postgres:
        host: matrix-stack-rw.matrix-stack.svc.cluster.local
        port: 5432
        user: matrix-stack
        password:
          secret: matrix-stack-app
          secretKey: password
        database: matrix_synapse
        sslMode: prefer

    # disable build-in postgresql
    postgres:
      enabled: false
