apiVersion: v1
kind: Secret
metadata:
    name: coturn
type: Opaque
stringData:
    coturn.conf: ENC[AES256_GCM,data:inQlGBDAw+fEW4fA6ZuzP4rFy7lgNpOeGwlQMKt7vgD/HfxKLC+pRMMnXx0pmJE20O2BXYKAmknEpbfmpX+5vFMOY48mKeLBpjpJ9dGBjVSXT6Ki01ePX5xYwXnp2sjLwUFM7q4IHbEsdQwFjiWAIEvYTemPfXRy+f0iDBkvHFlC4zj8MM0GHnViPKHS8QyXUTvdxBPWdVID/wU=,iv:8I4TZDTZFtQVwkAk4v6sKr0iW1VuUxgqQNinlT7f4S8=,tag:7GZz3O19tiNv7m/BtF63tQ==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeGxNa2VucEZtK2pJaXho
            WXJmbmVaU3JoSElWTDl3MDlLdGdic1dGYkFRCldkZENtN1Fqb1hJS2JjaUpXRmpX
            eEZnMjJidU5uQVhESXZqbkRFNXBuQkEKLS0tIE04L1lQNWtRbERocjFzb09OcHZH
            VlVrT05pSW0xUmliSFZ1Z3I1UlFJY28KG/ofiIxuNcJnvBHE0LnGuZMSY1UO65eL
            05R6dcBGgJ/HmoqxpgM/SQrRXn6HXbRhn1yK7tDbjNmEIeKAzFV1Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:44:15Z"
    mac: ENC[AES256_GCM,data:/ZhjPgqYQbEV5g+oxbFMlK2WOaJgHYzZG722g0sZiecgu+Xu3lBoAvK2C3QPGR5ri80j+OlMVz5aarFQxPg2xavmeGQfv58u2k7Vzw/NqLB3q4fQGGDDojoYbTZIJ8inMzx3AfmxuljKstsyaXYy5Ir/SXezjTQPJxIcPQxgGlc=,iv:lZUuXWyarOEfKZr+Io8MiNijyQJeTVtAbHQKHT3DfH0=,tag:9vi6RB9w8Fx1rlfAe+ObXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
