namespace: tuwunel

resources:
  - tuwunel.config-map.yaml
  - tuwunel.namespace.yaml
  - tuwunel.helm-release.yaml
  - tuwunel.helm-repository.yaml
  - tuwunel.secret.yaml
  - tuwunel.ingress-route-tcp.yaml
