apiVersion: v1
kind: Secret
metadata:
    name: tuwunel
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:VJQ42AkibOHk3pfCzVDoSJlxc02pEFQQ9aanebH9Fn787qEpF+lG4jMLBp4ALHoNLljcYLh8zI1SzA==,iv:ym3SA8WA1tJBiCJ57b8NBVmFk1qWdNeP7rI7mVfP2lE=,tag:KZQ3reLL5CNFmsQTVCfTew==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTjIzZ3dieVV6UDV0Nk1x
            aUxpNEppNTRuK29TNWpwVEpDWlVNMWtpNkc0CkZFMGl3a0dDaDVrS0VBWDRwZWtq
            bkNYVzRBQWZ3KzZWR3pvOGloSEFzUWsKLS0tIDZSNVlNT2dtYlY4ck1FUWVLbzBC
            Q1ZlWE5JditvbnJOLzgvTDhkMk5HZDgK7xn9zo4Q2t4rjDlpmvvQd7RHgXoDeTfz
            TI3nm2ugxZeUkxUgYxTT5aoDheqn1dlMgbh48jXltVk3zXtGxdOMlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T23:46:11Z"
    mac: ENC[AES256_GCM,data:n9C1dDe7wKVr81dxg/NHlLj1VFI2/IUlqMMWnVnIpbPiPcw6ohMtzHLY5oBCQrEo1P4zLrV6TK9z4WqYpFZ2rcRHp/vDz7/Hs12DKoO/MQJa42jSaIdbex+EBaGDSdVDd+tgFEOsHm2fWXzr+DZpSWcr6Oq+42iMaQrkEp5KONA=,iv:+j7v4ZMXOZwrLNOYvouf8V1bQxHF2RsCY0uz7ypKbmM=,tag:BUxbZdB/bmcYqSgDlxJKKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
