apiVersion: v1
kind: ConfigMap
metadata:
  name: tuwunel
data:
  values.yaml: |
    image:
      repository: ghcr.io/matrix-construct/tuwunel
      tag: v1.5.0

    config:
      server_name: "matrix.sxmfmc.net"

      # Maximum upload size
      max_request_size: 20000000

      # Whether to allow users to register new accounts
      allow_registration: true

      # Whether to allow federating with other Matrix servers
      allow_federation: true
      trusted_servers: [ "matrix.org" ]
      #delegatedDomain: "matrix.sxmfmc.net"

    persistence:
      data:
        enabled: true
        size: 10Gi
        storageClass: longhorn
