apiVersion: v1
kind: Secret
metadata:
    name: tuwunel
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:TaV6ANBXAgHPvXXPh7iYeRbSbmh0cWIKXM/J2kn3tuJcP4TMLBIIfvvhryXVCOLCGbaWlRVQY1AO2k/nfygucPLJQt6blS3UHaA6OOuRMKtYvzt/SfwnzUH6BENkkNpTeAh13lb5HrS4MAGm7OHSRGyo1rKBZDZF/W+wWKeK4YTyPbKXpBbLpNsq68D1KqUHF7SoEov3sGv/qveCg30kuxTnRw6XOwsufQ/80pXEtDannzDkJSRtDwoX2ZGZ5+aCQktAjdpCxeo1ehVKqY+3uaOZUi7qxBQGvrnrXngStpO7UTKMZx+rdptGnk8iaTcJte1pB2sdP6f0tQcKLeJ6emmo11q8lARCGvvu898mcb9rX5x1VHCdKkyKcg==,iv:q3zKBVE1VSCZfYW+OMaoBSuYgDXQfK3ydK2vhrBfTf8=,tag:9SMzI/9uOSzwgiSouGxS3A==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTjIzZ3dieVV6UDV0Nk1x
            aUxpNEppNTRuK29TNWpwVEpDWlVNMWtpNkc0CkZFMGl3a0dDaDVrS0VBWDRwZWtq
            bkNYVzRBQWZ3KzZWR3pvOGloSEFzUWsKLS0tIDZSNVlNT2dtYlY4ck1FUWVLbzBC
            Q1ZlWE5JditvbnJOLzgvTDhkMk5HZDgK7xn9zo4Q2t4rjDlpmvvQd7RHgXoDeTfz
            TI3nm2ugxZeUkxUgYxTT5aoDheqn1dlMgbh48jXltVk3zXtGxdOMlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:40:20Z"
    mac: ENC[AES256_GCM,data:lMv+nnbNYS6pOrtsZS8D/0spU0EjCQKyccqaT3UpV7F+4vU+oD6EBOX43eMZEtkBSJ2/StFN3+GA3EiSpg9u8X3uhteGSH2y0tdwv2ETEehsRcZslOJds4ZY9Q+bDW8gHlMViLs3NtiHRkJ9GpRtbeVMd0Xb9Z3LFxK/pBjwlJ4=,iv:SdZj7EXv9F86KZI3YTWmzRqFPmk8Ty/kqyEPE9P8HJM=,tag:hPZytueUVs5XmvSDqAPlGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
