apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuwunel
  namespace: tuwunel
spec:
  chart:
    spec:
      chart: conduwuit
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tuwunel
      version: 2.1.0
  interval: 15m0s
  valuesFrom:
    - kind: ConfigMap
      name: tuwunel
      valuesKey: values.yaml
    - kind: Secret
      name: tuwunel
      valuesKey: values.yaml
