apiVersion: v1
kind: Secret
metadata:
    name: tuwunel
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:wNbG9jEgJuRBPlvFyehm8H5REYKye0il/cIhS+n/dDbgqptTHTMdMCA4CvjE6MWyW4sZjzBlCG8y/lOEObqcP1k/R9iyMjux,iv:rx0uTxNAmDO2VdeyAdcGM5sc+/YckH5ndDi+LPbTfNI=,tag:FHJf7qUr5F8scQJ8uWdF8Q==,type:str]
sops:
    age:
        - recipient: age1sl4vsymlq5h3vl343gyd9h6ne0za9wnrs3z50ehr9gkftfw77c5qa26554
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTjIzZ3dieVV6UDV0Nk1x
            aUxpNEppNTRuK29TNWpwVEpDWlVNMWtpNkc0CkZFMGl3a0dDaDVrS0VBWDRwZWtq
            bkNYVzRBQWZ3KzZWR3pvOGloSEFzUWsKLS0tIDZSNVlNT2dtYlY4ck1FUWVLbzBC
            Q1ZlWE5JditvbnJOLzgvTDhkMk5HZDgK7xn9zo4Q2t4rjDlpmvvQd7RHgXoDeTfz
            TI3nm2ugxZeUkxUgYxTT5aoDheqn1dlMgbh48jXltVk3zXtGxdOMlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T00:13:54Z"
    mac: ENC[AES256_GCM,data:nWWEahlBuvQmMObDupfcpfeC/qenpEfaWzdteOQwlWTI1s3VLxGWX3QhK9SdQ2J5DancOrZg9lltu2qP0H2X6pF1hjk6fmOB3/yv38HSKWastCTSr/FMM3ijIVeyPv+VXP61xDip8wHC6GLd9VCCdFK+ys4v2UBVPT576t+S0g8=,iv:P5PrFIIQuPj5c31M7Y+RcCDsZw8i16MzkQ2eziA9XIc=,tag:b+MDIilInOWE5WAaokMUwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
