apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth-cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:QhKv0Cpt3PXNtjDg8yWRB6gs36PumkXkfxpZxDQ76nNFno8M7OP0rZvnMTpVZ1QW6a/NdGY=,iv:Q6PpSiZmmnRsjQe6QO5MCY2zlBX7z0ZP4AXNjG5mSeQ=,tag:QGG+cWd4+DnRtWvWxB89iQ==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxclQ1UDBzbVpoV0Z3ZFpp
            R29waFNIYUlTYWRhckMrVVN4STBhQ3JUOFRvCk9RTEUyTmdOcHI2UEcxdTRTQmdo
            ZHJ1QkRmTmZHeFdkVzFqY21Rc3YrWHMKLS0tIFFsUWcvS1lmSWIvalc1a0dJWmR4
            OElBN1paanI2bDFrVmdtdmt4NUxzUzgKSfnDOormemroOMf/Z2x1fBhU7zQJPwcV
            M7ZYgyXRbBMmxkxxiiM2lQtTn6Y2SramRYDamP1H/B6bM4Wma2K2vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:08:55Z"
    mac: ENC[AES256_GCM,data:HujuwP0EGpZ8GK9vD9qpKtAI/bZogJC2xY88P2fJQaC5UqCYJfEUSlXPEjBt2L6uBf2UoVxDQ56xsKLv3pt7NnArKG3+lHZTuQMbflPM1CtH1+RLd4Iy9ES5s2D4Iz+jlDwNlS3Kyl6+UmeLKsMxwFlnD5mlxrIGz3bYa4GiUbk=,iv:i+1hIklSUXZyPtz8LQXQXZ8UWI9Iv0MTUnthmGNZ+D0=,tag:f8B2W+Ne6sV1NAiKOawtyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
