apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth-cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:BL/wXlAZ8In8U0V//AFnxZFdcNjUPhPtofubh+HsIWNBceu8M5db8A==,iv:82Mr827nH1R3MvZu4zfZ2ZZCv0JvfFQ3g/Kd4c1aRjs=,tag:zdsyUpON38zIcp76pCI4CQ==,type:str]
sops:
    age:
        - recipient: age1jpvhzhyarcnr6vylq0cwpj86vnqzr5s5mw0kwcq2jzzwvm3as4cqjcrsxm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxclQ1UDBzbVpoV0Z3ZFpp
            R29waFNIYUlTYWRhckMrVVN4STBhQ3JUOFRvCk9RTEUyTmdOcHI2UEcxdTRTQmdo
            ZHJ1QkRmTmZHeFdkVzFqY21Rc3YrWHMKLS0tIFFsUWcvS1lmSWIvalc1a0dJWmR4
            OElBN1paanI2bDFrVmdtdmt4NUxzUzgKSfnDOormemroOMf/Z2x1fBhU7zQJPwcV
            M7ZYgyXRbBMmxkxxiiM2lQtTn6Y2SramRYDamP1H/B6bM4Wma2K2vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T21:53:37Z"
    mac: ENC[AES256_GCM,data:nR2QNg4SrWVrPX2nukU4N4uG4bNeDYi/bwAwrc7rY0WO0NoNujPPl4FREGf1j+P9T1aUbXFHZjxpdmDYFRFgUe3FmF8KxEUfEguBEGl2mrlO75XTmaZQPxQ2bVe2nfamEAfBp8fCc7NrRNyw/aotBzZbt/r7m4IuGUEtnsUkRQc=,iv:sURk1zenJpTMZusjKtXGh6hDXMny1o5O+fohrWqCLmU=,tag:+MaHieXVocinabRkcK0PdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
